# Generated by Django 4.1.6 on 2023-03-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0003_alter_file_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
